@extends('layouts.shelter.app')
@section('title','Notifications')
@section('content')
<div class="sh-breadcrumb"><a href="{{ route('shelter.dashboard') }}">Dashboard</a><span>›</span><span>Notifications</span></div>
<div class="sh-heading"><div><h1>Notifications @include('shelter.partials.icon',['name'=>'notifications'])</h1><p>Stay up to date with your shelter.</p></div><form action="{{ route('shelter.notifications.readAll') }}" method="POST">@csrf @method('PATCH')<button type="submit" class="sh-button sh-primary">Mark All as Read</button></form></div>
<form class="sh-filters" method="GET" action="{{ route('shelter.notifications.index') }}" data-filters><label class="sh-field" style="flex:none;width:240px"><select name="status" aria-label="Notification status"><option value="all">All Notifications</option><option value="unread" @selected(request('status')==='unread')>Unread</option><option value="read" @selected(request('status')==='read')>Read</option></select></label><button type="submit" class="sh-button">Apply</button><a class="sh-button" href="{{ route('shelter.notifications.index') }}">Clear Filters</a></form>
<section class="sh-card">@forelse($notifications as $notification)<div class="d-flex align-items-start gap-3 p-4 border-bottom {{ $notification->is_read?'':'sh-stat-green' }}">@include('shelter.partials.icon',['name'=>'notifications','class'=>'text-success'])<div class="flex-grow-1"><strong>{{ $notification->title }}</strong>@unless($notification->is_read)<span class="sh-badge sh-green ms-2">Unread</span>@endunless<p class="mb-1 mt-1" style="color:var(--sh-text)">{{ $notification->message }}</p><small class="text-muted">{{ $notification->created_at->diffForHumans() }}</small>@if($notification->link)<a class="d-block mt-2" href="{{ $notification->link }}">View Details</a>@endif</div>@unless($notification->is_read)<form action="{{ route('shelter.notifications.read',['source'=>$notification->source,'notification'=>$notification->id]) }}" method="POST">@csrf @method('PATCH')<button class="sh-button sh-small" type="submit">Mark as Read</button></form>@endunless</div>@empty<div class="sh-empty">@include('shelter.partials.icon',['name'=>'notifications'])<strong>No notifications found</strong>You’re up to date.</div>@endforelse
@include('shelter.partials.pagination',['items'=>$notifications,'noun'=>'notifications'])</section>
@endsection
