<aside class="sh-card sh-detail" aria-label="Adoption Request Details"><div class="sh-detail-title"><h2><i class="bi bi-x-lg" style="color:#16a675"></i> Adoption Request Details</h2>@if(isset($closeUrl))<a href="{{ $closeUrl }}" aria-label="Close adoption request details"><i class="bi bi-x-lg"></i></a>@endif</div>
<div class="sh-detail-hero">@include('shelter.partials.animal-photo',['animal'=>$application->listing])<div><h3>{{ $application->listing->pet_name }} @if($application->listing->gender)<i class="bi bi-gender-{{ $application->listing->gender }}" style="color:#078aff;font-size:20px"></i>@endif</h3><p>{{ $application->listing->breed?->name ?? $application->listing->species?->name }} @if($application->listing->age) • {{ $application->listing->age }} @endif</p>@include('shelter.partials.status',['status'=>$application->listing->status,'statusLabel'=>['available'=>'Available for Adoption','pending'=>'Reserved','adopted'=>'Adopted','inactive'=>'Not Listed'][$application->listing->status]])</div></div>
<section class="sh-detail-section"><h3>@include('shelter.partials.icon',['name'=>'requests']) Applicant Information</h3><dl><dt>Name</dt><dd>{{ $application->applicant->name }}</dd><dt>Email</dt><dd>{{ $application->applicant->email }}</dd><dt>Phone</dt><dd>{{ $application->phone ?: $application->applicant->phone ?: 'Not provided' }}</dd><dt>Address</dt><dd>{{ $application->address ?: $application->applicant->address ?: 'Not provided' }}</dd></dl></section>
<section class="sh-detail-section"><h3>@include('shelter.partials.icon',['name'=>'document']) Application Details</h3><dl><dt>Applied On</dt><dd>{{ $application->created_at->format('M d, Y').' at '.$application->created_at->format('h:i A') }}</dd><dt>Pet Experience</dt><dd>{{ $application->pet_experience ?: 'Not provided' }}</dd><dt>Reason for Adoption</dt><dd>{{ $application->why_adopt ?: $application->message ?: 'Not provided' }}</dd><dt>Home Type</dt><dd>{{ ucfirst($application->home_type ?: 'Not provided') }}</dd><dt>Additional Notes</dt><dd>{{ $application->message ?: 'None' }}</dd>@if($full ?? false)<dt>Status</dt><dd>@include('shelter.partials.status',['status'=>$application->status])</dd>@endif
@if($full ?? false)@foreach(['has_yard'=>'Has a yard','living_situation'=>'Living situation','has_other_pets'=>'Other pets','other_pets_details'=>'Other pets details','has_children'=>'Children','children_ages'=>'Children ages','work_schedule'=>'Work schedule'] as $field=>$label)<dt>{{ $label }}</dt><dd>{{ in_array($field,['has_yard','has_other_pets','has_children'])?($application->$field===null?'Not provided':($application->$field?'Yes':'No')):($application->$field ?: 'Not provided') }}</dd>@endforeach @endif
</dl></section>
@if($application->shelter_response)<details class="sh-detail-section" @if($full ?? false) open @endif><summary class="small">Shelter Response</summary><p class="small text-break mt-2">{{ $application->shelter_response }}</p></details>@endif
@if(!in_array($application->status,['rejected','completed'])&&$application->listing->status!=='adopted')
<form method="POST" action="{{ route('shelter.applications.updateStatus',$application) }}" id="applicationStatusForm-{{ $application->id }}">@csrf @method('PUT')<details @if(($full ?? false)||$errors->has('shelter_response')) open @endif><summary class="small mb-2">Add a response / note</summary><label class="small d-block mb-1" for="shelterResponse-{{ $application->id }}">Response / notes (optional)</label><textarea class="sh-response" name="shelter_response" maxlength="1000" id="shelterResponse-{{ $application->id }}" placeholder="Add a note for the applicant...">{{ old('shelter_response',$application->shelter_response) }}</textarea></details><div class="sh-detail-actions"><button class="sh-button sh-danger" type="submit" name="status" value="rejected"><i class="bi bi-x-lg"></i> Reject</button>@if($application->status!=='approved')<button class="sh-button sh-outline-blue" type="submit" name="status" value="reviewing"><i class="bi bi-arrow-right"></i> Move to Reviewing</button><button class="sh-button sh-primary" type="submit" name="status" value="approved"><i class="bi bi-check-lg"></i> Approve</button>@endif</div></form>
@if($application->status==='approved')<form class="mt-3" method="POST" action="{{ route('shelter.applications.finalize',$application) }}" onsubmit="return confirm('Finalize this adoption? Other active requests for this animal will be rejected.')">@csrf<button class="sh-button sh-primary w-100" type="submit"><i class="bi bi-check-circle"></i> Finalize Adoption</button></form>@endif
@endif
</aside>
