@extends('layouts.shelter.app')
@section('title','Adoption History')
@section('content')
<div class="sh-breadcrumb"><a href="{{ route('shelter.dashboard') }}"><i class="bi bi-house-door-fill"></i> Dashboard</a><span>›</span><span>Adoption History</span></div>
<div class="sh-heading"><div><h1>Adoption History @include('shelter.partials.icon',['name'=>'history'])</h1><p>View all past adoption requests and their status.</p></div><div class="sh-note">@include('shelter.partials.icon',['name'=>'paw'])<span>“Every adoption<br>creates a happier tomorrow.”</span></div></div>
@include('shelter.partials.stats',['compact'=>true,'cards'=>[
['label'=>'Total Adoptions','value'=>$stats['total'],'icon'=>'paw','tone'=>'green','url'=>route('shelter.history.index')],
['label'=>'Successfully Adopted','value'=>$stats['completed'],'icon'=>'check','tone'=>'blue','url'=>route('shelter.history.index',['status'=>'completed'])],
['label'=>'Rejected','value'=>$stats['rejected'],'icon'=>'reject','tone'=>'red','url'=>route('shelter.history.index',['status'=>'rejected'])],
['label'=>'This Month','value'=>$stats['month'],'icon'=>'calendar','tone'=>'purple','url'=>route('shelter.history.index',['date_from'=>now()->startOfMonth()->toDateString(),'date_to'=>now()->endOfMonth()->toDateString()])]
]])
<form class="sh-filters" method="GET" action="{{ route('shelter.history.index') }}" data-filters style="margin-top:25px">
<label class="sh-field sh-search">@include('shelter.partials.icon',['name'=>'search'])<input type="search" name="search" value="{{ request('search') }}" placeholder="Search by pet name, adopter name..." maxlength="200" aria-label="Search adoption history"><button type="submit" aria-label="Search adoption history"><i class="bi bi-arrow-return-left"></i></button></label>
<label class="sh-field"><select name="status" aria-label="Adoption history status"><option value="">All Statuses</option><option value="completed" @selected(request('status')==='completed')>Adopted</option><option value="rejected" @selected(request('status')==='rejected')>Rejected</option></select></label>
<label class="sh-field"><select name="species_id" aria-label="Adoption history species"><option value="">All Species</option>@foreach($species as $item)<option value="{{ $item->id }}" @selected(request('species_id')==$item->id)>{{ $item->name }}</option>@endforeach</select></label>
<div class="sh-field sh-date-range">@include('shelter.partials.icon',['name'=>'calendar'])<input type="date" name="date_from" value="{{ request('date_from') }}" aria-label="From Date"><span>→</span><input type="date" name="date_to" value="{{ request('date_to') }}" aria-label="To Date"></div>
<a class="sh-button sh-filter-clear" href="{{ route('shelter.history.index') }}">Clear Filters</a></form>
<section class="sh-card"><div class="sh-table-wrap" style="padding-top:10px"><table class="sh-table"><thead><tr>@foreach(['#','Pet','Adopter','Adoption Date','Status','Notes','Actions'] as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>
@forelse($applications as $application)<tr><td>{{ $applications->firstItem()+$loop->index }}</td><td><div class="sh-pet">@include('shelter.partials.animal-photo',['animal'=>$application->listing])<div><strong>{{ $application->listing->pet_name }}</strong><small>{{ $application->listing->breed?->name ?? 'Mixed Breed' }}</small></div></div></td><td><div class="sh-pet">@include('shelter.partials.person',['person'=>$application->applicant])<div><strong>{{ $application->applicant->name }}</strong><small>{{ $application->address ?: $application->applicant->address }}</small></div></div></td><td class="text-nowrap">{{ ($application->completed_at??$application->decided_at??$application->updated_at)->format('M d, Y') }}</td><td>@include('shelter.partials.status',['status'=>$application->status==='rejected'?'rejected':'completed','statusLabel'=>$application->status==='rejected'?'Rejected':'Adopted','badgeIcon'=>$application->status==='rejected'?'reject':'check'])</td><td style="max-width:260px">{{ Str::limit($application->shelter_response ?: $application->message ?: '—',100) }}</td><td><div class="sh-actions"><a class="sh-button sh-small sh-view" href="{{ route('shelter.applications.show',$application) }}">View</a><div class="dropdown"><button type="button" class="sh-icon-button" data-bs-toggle="dropdown" aria-label="More actions for adoption {{ $application->id }}">@include('shelter.partials.icon',['name'=>'more'])</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{ route('shelter.listings.show',$application->listing) }}">View animal</a></li><li><a class="dropdown-item" href="{{ route('shelter.applications.show',$application) }}">View full request</a></li></ul></div></div></td></tr>
@empty<tr><td colspan="7"><div class="sh-empty">@include('shelter.partials.icon',['name'=>'history'])<strong>No adoption history found</strong>Finalized and rejected requests will appear here.</div></td></tr>@endforelse
</tbody></table></div>@include('shelter.partials.pagination',['items'=>$applications])</section>
@endsection
