@extends('layouts.shelter.app')
@section('title','Adoption Requests')
@section('content')
<div class="sh-breadcrumb"><a href="{{ route('shelter.dashboard') }}"><i class="bi bi-house-door-fill"></i> Dashboard</a><span>›</span><span>Adoption Requests</span></div>
<div class="sh-heading"><div><h1>Adoption Requests @include('shelter.partials.icon',['name'=>'requests'])</h1><p>Review and manage adoption applications from potential pet owners.</p></div></div>
<div class="sh-request-stats">@include('shelter.partials.stats',['compact'=>true,'cards'=>[
['label'=>'Total Requests','value'=>$stats['total'],'icon'=>'document','tone'=>'blue','url'=>route('shelter.applications.index')],
['label'=>'Pending','value'=>$stats['pending'],'icon'=>'pending','tone'=>'amber','url'=>route('shelter.applications.index',['status'=>'pending'])],
['label'=>'Reviewing','value'=>$stats['reviewing'],'icon'=>'reviewing','tone'=>'blue','url'=>route('shelter.applications.index',['status'=>'reviewing'])],
['label'=>'Approved','value'=>$stats['approved'],'icon'=>'check','tone'=>'green','url'=>route('shelter.applications.index',['status'=>'approved'])],
['label'=>'Rejected','value'=>$stats['rejected'],'icon'=>'reject','tone'=>'red','url'=>route('shelter.applications.index',['status'=>'rejected'])]
]])</div>
<div class="sh-tabs-row"><nav class="sh-tabs" aria-label="Application status">@foreach([''=>'All','pending'=>'Pending','reviewing'=>'Reviewing','approved'=>'Approved','rejected'=>'Rejected'] as $value=>$label)<a class="{{ request('status','')===$value?'active':'' }}" href="{{ route('shelter.applications.index',array_filter(['status'=>$value,'search'=>request('search')],fn($v)=>$v!==null&&$v!=='')) }}">{{ $label }} ({{ $stats[$value?:'total'] }})</a>@endforeach</nav>
<form class="sh-filters" method="GET" action="{{ route('shelter.applications.index') }}" data-filters><input type="hidden" name="status" value="{{ request('status') }}"><label class="sh-field sh-search">@include('shelter.partials.icon',['name'=>'search'])<input type="search" name="search" placeholder="Search by applicant name, pet name..." value="{{ request('search') }}" aria-label="Search adoption requests" maxlength="200"><button type="submit" aria-label="Search adoption requests"><i class="bi bi-arrow-return-left"></i></button></label>@if(request('search'))<a class="sh-button sh-small" href="{{ route('shelter.applications.index') }}">Clear</a>@endif</form></div>
<div class="sh-request-grid {{ !$selected?'no-detail':'' }}"><section class="sh-card"><div class="sh-table-wrap" style="padding-top:12px"><table class="sh-table sh-requests-table"><thead><tr>@foreach(['#','Pet','Applicant','Applied On','Status','Actions'] as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>
@forelse($applications as $application)<tr><td>{{ $applications->firstItem()+$loop->index }}</td><td><div class="sh-pet">@include('shelter.partials.animal-photo',['animal'=>$application->listing])<div><strong>{{ $application->listing->pet_name }}</strong><small>{{ $application->listing->breed?->name ?? 'Mixed Breed' }}</small></div></div></td><td><div class="sh-pet">@include('shelter.partials.person',['person'=>$application->applicant])<div><strong>{{ $application->applicant->name }}</strong><small>{{ $application->applicant->email }}<br>{{ $application->phone ?: $application->applicant->phone }}</small></div></div></td><td class="text-nowrap">{{ $application->created_at->format('M d, Y') }}<br>{{ $application->created_at->format('h:i A') }}</td><td>@include('shelter.partials.status',['status'=>$application->status])</td><td><div class="sh-actions"><a class="sh-button sh-small sh-view" href="{{ route('shelter.applications.index',array_merge(request()->except(['selected','panel']),['selected'=>$application->id])) }}">View</a><div class="dropdown"><button type="button" class="sh-icon-button" data-bs-toggle="dropdown" aria-label="More actions for application {{ $application->id }}">@include('shelter.partials.icon',['name'=>'more'])</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{ route('shelter.applications.show',$application) }}">Full application</a></li><li><a class="dropdown-item" href="{{ route('shelter.listings.show',$application->listing) }}">View animal</a></li></ul></div></div></td></tr>
@empty<tr><td colspan="6"><div class="sh-empty">@include('shelter.partials.icon',['name'=>'requests'])<strong>No requests found</strong>Try clearing your filters.</div></td></tr>@endforelse
</tbody></table></div>@include('shelter.partials.pagination',['items'=>$applications,'noun'=>'requests'])</section>
@if($selected)@include('shelter.applications.detail',['application'=>$selected,'closeUrl'=>route('shelter.applications.index',array_merge(request()->except('selected'),['panel'=>'closed']))])@endif
</div>
@endsection
