@extends('layouts.owner.app')
@section('title','Dashboard')
@section('content')
<div class="op-heading"><div><h1>Welcome back, {{ Str::before(Auth::user()->name,' ') }}! 👋</h1><p>Here’s what’s happening with your pets today.</p></div><div class="op-note">@include('owner.partials.icon',['name'=>'paw'])<span>“Good care today,<br>a healthier tomorrow.”</span></div></div>
@if($search!=='')<section class="op-card op-search-results"><h2>Search results for “{{ $search }}”</h2>@forelse($searchResults as $result)<a href="{{ $result->url }}"><span>{{ $result->name }}</span><small>{{ $result->type }}</small></a>@empty<p>No matching pets, veterinarians, products or care tips found.</p>@endforelse<a href="{{ route('owner.dashboard') }}">Clear search</a></section>@endif
@if($notifications)@include('owner.partials.notifications')@endif
<div class="op-stats">@foreach([
 ['My Pets',$stats['pets'],'paw','green','Manage your pets',route('owner.pets.index')],
 ['Upcoming Visits',$stats['upcoming'],'calendar','blue','View appointments',route('owner.appointments.index')],
 ['Vaccinations Due',$stats['vaccinations'],'vaccination','red','Stay up to date',route('owner.pets.index',['status'=>'vaccination_due','view'=>'health'])],
 ['Health Records',$stats['health_records'],'document','amber','View records',route('owner.health.overview')],
 ['Cart Items',$stats['cart_items'],'cart-fill','purple','Go to cart',route('owner.cart.index')]
] as [$label,$count,$icon,$tone,$description,$url])<a class="op-stat op-bg-{{ $tone }}" href="{{ $url }}"><span class="op-stat-icon">@include('owner.partials.icon',['name'=>$icon])</span><div><span class="op-stat-label">{{ $label }}</span><strong>{{ $count }}</strong></div><small>{{ $description }}<i class="bi bi-chevron-right"></i></small></a>@endforeach</div>
<div class="op-dashboard-grid"><section class="op-card"><div class="op-card-header"><h2>@include('owner.partials.icon',['name'=>'paw']) My Pets</h2><a href="{{ route('owner.pets.index') }}">View All ›</a></div><div class="op-mini-pets">@forelse($pets as $pet)<article class="op-mini-pet">@include('owner.partials.photo',['pet'=>$pet])<strong>{{ $pet->name }}</strong><small>{{ $pet->breed?->name ?: $pet->species?->name }}</small><small>@include('owner.partials.age',['pet'=>$pet]) • {{ ucfirst($pet->gender??'') }}</small>@include('owner.partials.health',['pet'=>$pet])<a class="op-button op-small" href="{{ route('owner.pets.show',$pet) }}">View Profile</a></article>@empty<div class="op-empty" style="grid-column:1/-1">No pets added yet.<br><a href="{{ route('owner.pets.create') }}">Add your first pet</a></div>@endforelse</div></section>
<section class="op-card"><div class="op-card-header"><h2>@include('owner.partials.icon',['name'=>'calendar']) Upcoming Appointments</h2><a href="{{ route('owner.appointments.index') }}">View All ›</a></div><div class="op-visits">@forelse($appointments as $appointment)<div class="op-visit">@include('owner.partials.photo',['pet'=>$appointment->pet])<div><strong>{{ $appointment->pet->name }}</strong><small>with {{ $appointment->vet->name }}</small><time><i class="bi bi-calendar3"></i> {{ $appointment->appointment_date->format('d M Y') }} &nbsp;<i class="bi bi-clock"></i> {{ \Carbon\Carbon::parse($appointment->appointment_time)->format('h:i A') }}</time></div><span class="op-badge {{ $appointment->status==='pending'?'op-amber':'op-green' }}">{{ $appointment->status==='approved'?'Confirmed':ucfirst($appointment->status) }}</span><div class="dropdown"><button type="button" class="op-more" data-bs-toggle="dropdown" aria-label="Appointment actions for {{ $appointment->pet->name }}"><i class="bi bi-three-dots"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{ route('owner.appointments.index',['status'=>$appointment->status]) }}">View appointments</a></li><li><a class="dropdown-item" href="{{ route('owner.browse-vets.show',$appointment->vet) }}">View veterinarian</a></li></ul></div></div>@empty<div class="op-empty">No upcoming appointments.<br><a href="{{ route('owner.appointments.create') }}">Book a visit</a></div>@endforelse</div></section>
<section class="op-card"><div class="op-card-header"><h2>@include('owner.partials.icon',['name'=>'notifications']) Upcoming Reminders</h2><a href="{{ route('owner.pets.index',['status'=>'vaccination_due','view'=>'health']) }}">View All</a></div><div class="op-reminders">@forelse($reminders as $reminder)<a class="op-reminder" href="{{ route('owner.health.index',$reminder->pet) }}"><span>@include('owner.partials.icon',['name'=>'vaccination'])</span><div>{{ $reminder->pet->name }}’s {{ $reminder->vaccine_name }} vaccination due<small>{{ $reminder->next_due_date->isToday()?'Today':($reminder->next_due_date->lt(today())?'Overdue by '.$reminder->next_due_date->diffForHumans(today(),true):($reminder->next_due_date->isTomorrow()?'Tomorrow':'In '.$reminder->next_due_date->diffForHumans(today(),true))) }}</small></div></a>@empty<div class="op-empty">No vaccinations due in the next 30 days.</div>@endforelse</div></section></div>
<div class="op-dashboard-bottom"><section class="op-card"><div class="op-card-header"><h2>@include('owner.partials.icon',['name'=>'activity']) Recent Health Activity</h2><a href="{{ route('owner.health.overview') }}">View All</a></div><div class="op-activity">@forelse($activity as $item)<a href="{{ $item->url }}">@include('owner.partials.icon',['name'=>$item->icon])<span>{{ $item->title }}</span><time>{{ $item->date->format('d M Y') }} &emsp; <i class="bi bi-clock"></i> {{ $item->date->format('h:i A') }}</time></a>@empty<div class="op-empty">Your pets’ health updates will appear here.</div>@endforelse</div></section>
<section class="op-card"><div class="op-card-header"><h2>@include('owner.partials.icon',['name'=>'bolt']) Quick Actions</h2></div><div class="op-quick">@foreach([
 ['Add Pet','paw','green',route('owner.pets.create')],['Book Appointment','calendar','blue',route('owner.appointments.create')],['Browse Products','cart-fill','red',route('owner.products.index')],
 ['Add Health Record','document','amber',route('owner.health.overview')],['View Care Tips','lightbulb-fill','purple',route('owner.care.index')],['Find Veterinarians','vet','green',route('owner.browse-vets')]
] as [$label,$icon,$tone,$url])<a class="op-bg-{{ $tone }}" href="{{ $url }}">@include('owner.partials.icon',['name'=>$icon]){{ $label }}</a>@endforeach</div></section></div>
<div class="op-banner"><div class="op-banner-art">@if($pets->isNotEmpty())@foreach($pets->take(2) as $pet)@include('owner.partials.photo',['pet'=>$pet])@endforeach @else @include('owner.partials.companions') @endif</div><div><strong>Because they give us unconditional love</strong><p>Let’s give them a healthier, happier life.</p></div><a class="op-button op-primary" href="{{ route('owner.care.index') }}">Explore Pet Care Tips <i class="bi bi-arrow-right"></i></a></div>
@endsection
