@extends('layouts.shelter.app')
@section('title','Dashboard')
@section('content')
<div class="sh-heading"><div><h1>Welcome back, {{ Auth::user()->shelterProfile?->shelter_name ?: Auth::user()->name }} <span style="color:#499c76">❧</span></h1><p>Here’s what’s happening with your shelter today.</p></div><div class="sh-quote">Pets<br>People<br>Brighter Futures ♥</div></div>
@include('shelter.partials.stats',['cards'=>[
['label'=>'Total Animals','value'=>$stats['total'],'icon'=>'paw','tone'=>'green','description'=>'Lives in our care','ghost'=>'requests','url'=>route('shelter.listings.index')],
['label'=>'Available for Adoption','value'=>$stats['available'],'icon'=>'dashboard','tone'=>'blue','description'=>'Ready for their forever home','url'=>route('shelter.listings.index',['status'=>'available'])],
['label'=>'Pending Requests','value'=>$stats['pending'],'icon'=>'document','tone'=>'amber','description'=>'Awaiting your review','ghost'=>'requests','url'=>route('shelter.applications.index',['status'=>'pending'])],
['label'=>'Under Treatment','value'=>$stats['under_treatment'],'icon'=>'medical','tone'=>'red','description'=>'Receiving medical care','ghost'=>'health','url'=>route('shelter.listings.index',['health_state'=>'under_treatment'])],
['label'=>'Adopted','value'=>$stats['adopted'],'icon'=>'heart','tone'=>'purple','description'=>'Happy new beginnings','url'=>route('shelter.listings.index',['status'=>'adopted'])]
]])
<div class="sh-dashboard-main">
<section class="sh-card"><div class="sh-card-header"><h2>@include('shelter.partials.icon',['name'=>'requests']) Recent Adoption Requests</h2><a href="{{ route('shelter.applications.index') }}">View All</a></div>
<div class="sh-table-wrap"><table class="sh-table"><thead><tr><th>Applicant</th><th>Pet</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($recentApplications as $application)<tr><td><div class="sh-pet">@include('shelter.partials.person',['person'=>$application->applicant])<span>{{ $application->applicant->name }}</span></div></td><td><div class="sh-pet">@include('shelter.partials.animal-photo',['animal'=>$application->listing])<div><strong>{{ $application->listing->pet_name }}</strong><small>{{ $application->listing->breed?->name }}</small></div></div></td><td>{{ $application->created_at->format('M d, Y') }}</td><td>@include('shelter.partials.status',['status'=>$application->status])</td><td><a class="sh-button sh-small sh-outline-blue" href="{{ route('shelter.applications.index',['selected'=>$application->id]) }}">View</a></td></tr>
@empty<tr><td colspan="5"><div class="sh-empty">No adoption requests yet.</div></td></tr>@endforelse
</tbody></table></div></section>
<section class="sh-card"><div class="sh-card-header"><h2>@include('shelter.partials.icon',['name'=>'warning','class'=>'text-warning']) Animals Requiring Attention</h2><a href="{{ route('shelter.care-status.index',['status'=>'pending']) }}">View All</a></div><div class="sh-attention">
@foreach($attention as $log)<a class="sh-attention-row" href="{{ route('shelter.care-status.show',$log) }}">@include('shelter.partials.animal-photo',['animal'=>$log->listing])<div><strong>{{ $log->listing?->pet_name ?? $log->animal_name }}</strong><small>{{ $log->listing?->breed?->name }}</small></div><div>@include('shelter.partials.status',['status'=>$log->type,'statusLabel'=>ucfirst($log->type).' Due'])<small><i class="bi bi-calendar3"></i> {{ ($log->due_date??$log->log_date)->diffForHumans() }}</small></div>@include('shelter.partials.icon',['name'=>'chevron'])</a>@endforeach
@foreach($attentionAnimals as $animal)<a class="sh-attention-row" href="{{ route('shelter.care-status.create',['listing_id'=>$animal->id]) }}">@include('shelter.partials.animal-photo',['animal'=>$animal])<div><strong>{{ $animal->pet_name }}</strong><small>{{ $animal->breed?->name }}</small></div><div>@include('shelter.partials.status',['status'=>$animal->health_state])<small>Please update care records</small></div>@include('shelter.partials.icon',['name'=>'chevron'])</a>@endforeach
@if($attention->isEmpty()&&$attentionAnimals->isEmpty())<div class="sh-empty">@include('shelter.partials.icon',['name'=>'check'])No animals require attention.</div>@endif
</div></section></div>
<div class="sh-dashboard-bottom"><section class="sh-card"><div class="sh-card-header"><h2>@include('shelter.partials.icon',['name'=>'clock']) Recent Activity</h2><a href="{{ route('shelter.care-status.index') }}">View All</a></div><div class="sh-activity">@forelse($activity as $item)<a href="{{ $item->url }}"><span class="sh-dot"></span>@include('shelter.partials.icon',['name'=>$item->icon])<span>{{ $item->text }}</span><time>{{ $item->date->diffForHumans() }}</time></a>@empty<div class="sh-empty">Your recent activity will appear here.</div>@endforelse</div></section>
<section class="sh-card"><div class="sh-card-header"><h2>@include('shelter.partials.icon',['name'=>'bolt','class'=>'text-warning']) Quick Actions</h2></div><div class="sh-quick"><a class="sh-stat-green text-success" href="{{ route('shelter.listings.create') }}">@include('shelter.partials.icon',['name'=>'plus-circle-fill'])<strong>+ Add Animal</strong><small>Register a new animal in your care</small></a><a class="sh-stat-blue text-primary" href="{{ route('shelter.care-status.create') }}">@include('shelter.partials.icon',['name'=>'document'])<strong>+ Add Care Record</strong><small>Log medical care, feeding, or notes</small></a><a class="sh-stat-purple" style="color:#6436bb" href="{{ route('shelter.applications.index') }}">@include('shelter.partials.icon',['name'=>'requests'])<strong>View Adoption Requests</strong><small>Review and respond to applications</small></a></div></section></div>
<div class="sh-quote" style="text-align:right;margin-top:15px">Same Paws<br>A Kinder World ♥</div>
@endsection
