@extends('layouts.shelter.app')
@section('title','My Animals')
@section('content')
<div class="sh-breadcrumb"><a href="{{ route('shelter.dashboard') }}">Dashboard</a><span>›</span><a href="{{ route('shelter.listings.index') }}">My Animals</a><span>›</span><span>{{ $listing->exists?'Edit Animal':'Add Animal' }}</span></div>
<div class="sh-heading"><div><h1>{{ $listing->exists?'Edit Animal':'Add Animal' }} @include('shelter.partials.icon',['name'=>'paw'])</h1><p>{{ $listing->exists?'Update this animal’s profile and care information.':'Register a new animal in your shelter.' }}</p></div><a class="sh-button" href="{{ route('shelter.listings.index') }}">Back to Animals</a></div>
<form class="sh-card sh-form-card" method="POST" enctype="multipart/form-data" action="{{ $listing->exists?route('shelter.listings.update',$listing):route('shelter.listings.store') }}">@csrf @if($listing->exists)@method('PUT')@endif
<div class="sh-form-grid">
<div><label for="pet_name">Animal Name *</label><input id="pet_name" name="pet_name" required maxlength="255" value="{{ old('pet_name',$listing->pet_name) }}"></div>
<div><label for="species_id">Species *</label><select id="species_id" name="species_id" required><option value="">Select species</option>@foreach($species as $item)<option value="{{ $item->id }}" @selected(old('species_id',$listing->species_id)==$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label for="breed_id">Breed</label><select id="breed_id" name="breed_id"><option value="">Select breed (optional)</option>@foreach($breeds as $item)<option value="{{ $item->id }}" data-species="{{ $item->species_id }}" @selected(old('breed_id',$listing->breed_id)==$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label for="gender">Gender</label><select id="gender" name="gender"><option value="">Not specified</option><option value="male" @selected(old('gender',$listing->gender)==='male')>Male</option><option value="female" @selected(old('gender',$listing->gender)==='female')>Female</option></select></div>
<div><label for="age">Age</label><input id="age" name="age" value="{{ old('age',$listing->age) }}" maxlength="50" placeholder="e.g. 2 years"></div>
<div><label for="health_state">Health Status *</label><select id="health_state" name="health_state" required>@foreach(['healthy'=>'Healthy','under_treatment'=>'Under Treatment','vaccination_due'=>'Vaccination Due'] as $value=>$text)<option value="{{ $value }}" @selected(old('health_state',$listing->health_state)===$value)>{{ $text }}</option>@endforeach</select></div>
<div><label for="status">Adoption Status *</label><select id="status" name="status" required>@foreach(['available'=>'Available','pending'=>'Reserved','inactive'=>'Not Listed']+($listing->status==='adopted'?['adopted'=>'Adopted']:[]) as $value=>$text)<option value="{{ $value }}" @selected(old('status',$listing->status)===$value)>{{ $text }}</option>@endforeach</select><small class="text-muted">Adoptions are finalized from an approved adoption request.</small></div>
<div><label for="health_status">Health Notes</label><input id="health_status" name="health_status" value="{{ old('health_status',$listing->health_status) }}" maxlength="255" placeholder="Vaccination, diet or medical information"></div>
<div class="full"><label for="description">About this Animal</label><textarea id="description" name="description" rows="4" maxlength="5000">{{ old('description',$listing->description) }}</textarea></div>
@if($listing->images->isNotEmpty())<div class="full"><label>Current Photos</label><div class="sh-gallery">@foreach($listing->images as $image)<div><img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($image->image_path) }}" alt="{{ $listing->pet_name }}"><label class="mt-2"><input type="checkbox" name="remove_images[]" value="{{ $image->id }}" @checked(in_array($image->id,old('remove_images',[])))> Remove photo</label></div>@endforeach</div></div>@endif
<div class="full"><label for="images">Photos</label><input type="file" id="images" name="images[]" multiple accept="image/jpeg,image/png,image/webp"><small class="text-muted">Up to 6 photos in total, 5 MB each. JPG, PNG or WebP. After a validation error, reselect new photo files.</small><div class="sh-gallery mt-3" id="imagePreviews"></div></div>
</div><div class="sh-form-actions"><a class="sh-button" href="{{ route('shelter.listings.index') }}">Cancel</a><button type="submit" class="sh-button sh-primary">{{ $listing->exists?'Save Changes':'Add Animal' }}</button></div></form>
@endsection
@push('scripts')<script>
const speciesInput=document.getElementById('species_id'),breedInput=document.getElementById('breed_id');
const breedOptions=Array.from(breedInput.options).slice(1).map(option=>({id:option.value,text:option.textContent,species:option.dataset.species}));
function updateBreeds(keep){const selected=keep?breedInput.value:'';breedInput.replaceChildren(new Option('Select breed (optional)',''));breedOptions.filter(option=>option.species===speciesInput.value).forEach(option=>breedInput.add(new Option(option.text,option.id,false,option.id===selected)));}
speciesInput.addEventListener('change',()=>updateBreeds(false));updateBreeds(true);
document.getElementById('images').addEventListener('change',event=>{const previews=document.getElementById('imagePreviews');previews.replaceChildren();Array.from(event.target.files).slice(0,6).forEach(file=>{if(!file.type.startsWith('image/'))return;const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt='New animal photo';image.onload=()=>URL.revokeObjectURL(image.src);previews.append(image);});});
</script>@endpush
