@extends('layouts.shelter.app')
@section('title','Care Records')
@section('content')
<div class="sh-breadcrumb"><a href="{{ route('shelter.dashboard') }}">Dashboard</a><span>›</span><a href="{{ route('shelter.care-status.index') }}">Care Records</a><span>›</span><span>{{ $log->exists?'Edit':'Add' }} Care Record</span></div>
<div class="sh-heading"><div><h1>{{ $log->exists?'Edit':'Add' }} Care Record @include('shelter.partials.icon',['name'=>'care'])</h1><p>Keep feeding, grooming and medical care up to date.</p></div><a class="sh-button" href="{{ route('shelter.care-status.index') }}">Back to Care Records</a></div>
<form class="sh-card sh-form-card" method="POST" action="{{ $log->exists?route('shelter.care-status.update',$log):route('shelter.care-status.store') }}">@csrf @if($log->exists)@method('PUT')@endif
<div class="sh-form-grid"><div><label for="listing_id">Animal *</label><select id="listing_id" name="listing_id" required><option value="">Select animal</option>@foreach($listings as $animal)<option value="{{ $animal->id }}" @selected(old('listing_id',$log->listing_id)==$animal->id)>{{ $animal->pet_name }}</option>@endforeach</select>@if($listings->isEmpty())<small><a href="{{ route('shelter.listings.create') }}">Add an animal first.</a></small>@endif</div>
<div><label for="type">Care Type *</label><select id="type" name="type" required><option value="">Select care type</option>@foreach(['feeding','grooming','medical','vaccination','other'] as $value)<option value="{{ $value }}" @selected(old('type',$log->type)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
<div><label for="log_date">Date *</label><input id="log_date" type="date" name="log_date" value="{{ old('log_date',$log->log_date?->toDateString()) }}" required></div><div><label for="log_time">Time *</label><input id="log_time" type="time" name="log_time" value="{{ old('log_time',substr($log->log_time??'',0,5)) }}" required></div>
<div><label for="staff_name">Staff *</label><input id="staff_name" name="staff_name" maxlength="255" value="{{ old('staff_name',$log->staff_name) }}" required></div><div><label for="status">Status *</label><select name="status" id="status" required>@foreach(['completed'=>'Completed','pending'=>'Pending','follow_up'=>'Follow-up'] as $value=>$text)<option value="{{ $value }}" @selected(old('status',$log->status)===$value)>{{ $text }}</option>@endforeach</select></div>
<div><label for="due_date">Due / Follow-up Date</label><input id="due_date" type="date" name="due_date" value="{{ old('due_date',$log->due_date?->toDateString()) }}"><small class="text-muted">Required for follow-up records.</small></div>
<div class="full"><label for="notes">Care Details *</label><textarea id="notes" name="notes" rows="5" maxlength="2000" required>{{ old('notes',$log->notes) }}</textarea></div></div>
<div class="sh-form-actions"><a class="sh-button" href="{{ route('shelter.care-status.index') }}">Cancel</a><button class="sh-button sh-primary" type="submit">Save Care Record</button></div></form>
@endsection
@push('scripts')<script>const careStatus=document.getElementById('status'),dueDate=document.getElementById('due_date'),logDate=document.getElementById('log_date');function syncCareDates(){dueDate.required=careStatus.value==='follow_up';dueDate.min=logDate.value;if(careStatus.value==='completed')logDate.max=@json(today()->toDateString());else logDate.removeAttribute('max');}careStatus.addEventListener('change',syncCareDates);logDate.addEventListener('change',syncCareDates);syncCareDates();</script>@endpush
