@extends('layouts.shelter.app')
@section('title','Care Records')
@section('content')
<div class="sh-breadcrumb"><a href="{{ route('shelter.dashboard') }}"><i class="bi bi-house-door-fill"></i> Dashboard</a><span>›</span><span>Care Records</span></div>
<div class="sh-heading"><div><h1>Care Records @include('shelter.partials.icon',['name'=>'care'])</h1><p>Track feeding, grooming, and medical care for shelter animals.</p></div><div class="sh-heading-actions"><div class="sh-note">Healthy care.<br>Happier tomorrows. <i class="bi bi-heart fs-4"></i></div><a class="sh-button sh-primary sh-button-large" href="{{ route('shelter.care-status.create') }}">@include('shelter.partials.icon',['name'=>'plus']) Add Care Record</a></div></div>
<form class="sh-filters" id="careFilters" method="GET" action="{{ route('shelter.care-status.index') }}" data-filters>
<label class="sh-field sh-search">@include('shelter.partials.icon',['name'=>'search'])<input name="search" type="search" value="{{ request('search',request('animal')) }}" placeholder="Search care records..." maxlength="200" aria-label="Search care records"><button type="submit" aria-label="Apply care filters"><i class="bi bi-arrow-return-left"></i></button></label>
<label class="sh-field">@include('shelter.partials.icon',['name'=>'paw'])<select name="listing_id" aria-label="Animal"><option value="">Animal</option>@foreach($listings as $animal)<option value="{{ $animal->id }}" @selected(request('listing_id')==$animal->id)>{{ $animal->pet_name }}</option>@endforeach</select></label>
<label class="sh-field">@include('shelter.partials.icon',['name'=>'tag'])<select name="type" aria-label="Care Type"><option value="">Care Type</option>@foreach(['feeding','grooming','medical','vaccination','other'] as $value)<option value="{{ $value }}" @selected(request('type')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label>
<label class="sh-field">@include('shelter.partials.icon',['name'=>'calendar'])<select name="period" aria-label="Date Range"><option value="all">Date Range</option>@foreach(['today'=>'Today','week'=>'This Week','month'=>'This Month','custom'=>'Custom Dates'] as $value=>$label)<option value="{{ $value }}" @selected(request('period')===$value)>{{ $label }}</option>@endforeach</select></label>
<label class="sh-field">@include('shelter.partials.icon',['name'=>'check'])<select name="status" aria-label="Care Status"><option value="">Status</option>@foreach(['completed'=>'Completed','pending'=>'Pending','follow_up'=>'Follow-up'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></label>
<a class="sh-button sh-filter-clear" href="{{ route('shelter.care-status.index') }}">Clear Filters</a>
<label class="sh-field sh-date-range" data-custom-dates @if(request('period')!=='custom' && !request('date_from') && !request('date_to')) hidden @endif>@include('shelter.partials.icon',['name'=>'calendar'])<input type="date" name="date_from" value="{{ request('date_from') }}" aria-label="Care from date"><span>→</span><input type="date" name="date_to" value="{{ request('date_to') }}" aria-label="Care to date"></label>
</form>
<section class="sh-card"><div class="sh-card-header"><h2>@include('shelter.partials.icon',['name'=>'care']) All Care Records</h2><label class="sh-sort">Sort by: <select form="careFilters" name="sort" aria-label="Sort care records" onchange="document.getElementById('careFilters').requestSubmit()"><option value="newest">Newest First</option><option value="oldest" @selected(request('sort')==='oldest')>Oldest First</option></select></label></div>
<div class="sh-table-wrap"><table class="sh-table sh-care-table"><thead><tr>@foreach(['#','Animal','Care Type','Details','Date','Time','Staff','Status','Actions'] as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>
@forelse($logs as $log)<tr><td>{{ $logs->firstItem()+$loop->index }}</td><td><div class="sh-pet">@include('shelter.partials.animal-photo',['animal'=>$log->listing])<div><strong>{{ $log->listing?->pet_name??$log->animal_name }}</strong><small>{{ $log->listing?->breed?->name }}</small></div></div></td><td>@include('shelter.partials.status',['status'=>$log->type,'badgeIcon'=>$log->type])</td><td style="max-width:240px">{{ Str::limit($log->notes,95) }}</td><td class="text-nowrap">{{ $log->log_date->format('M d, Y') }}</td><td class="text-nowrap">{{ $log->log_time?\Carbon\Carbon::parse($log->log_time)->format('h:i A'):'—' }}</td><td>{{ $log->staff_name ?: '—' }}</td><td>@include('shelter.partials.status',['status'=>$log->status])</td><td><div class="sh-actions"><a class="sh-button sh-small sh-view" href="{{ route('shelter.care-status.show',$log) }}">View</a><a class="sh-button sh-small" href="{{ route('shelter.care-status.edit',$log) }}">Edit</a><div class="dropdown"><button type="button" class="sh-icon-button" data-bs-toggle="dropdown" aria-label="More actions for care record {{ $log->id }}">@include('shelter.partials.icon',['name'=>'more'])</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{ route('shelter.care-status.edit',$log) }}">Update status</a></li><li><form method="POST" action="{{ route('shelter.care-status.destroy',$log) }}" onsubmit="return confirm('Delete this care record? This cannot be undone.')">@csrf @method('DELETE')<button type="submit" class="dropdown-item text-danger">Delete record</button></form></li></ul></div></div></td></tr>
@empty<tr><td colspan="9"><div class="sh-empty">@include('shelter.partials.icon',['name'=>'care'])<strong>No care records found</strong>Try another filter or add a care record.</div></td></tr>@endforelse
</tbody></table></div>@include('shelter.partials.pagination',['items'=>$logs])</section>
@endsection
