@extends('layouts.owner.app')
@section('title', 'Adopt a Pet')
@push('styles')
@include('owner.partials.discovery-styles')
@endpush
@section('content')
<div class="od-page">
<div class="op-breadcrumb"><a href="{{ route('owner.dashboard') }}"><i class="bi bi-house-door-fill"></i> Dashboard</a><i class="bi bi-chevron-right"></i><span>Adopt a Pet</span></div>
<div class="op-heading"><div><h1>@include('owner.partials.icon',['name'=>'dashboard']) Adopt a Pet</h1><p>Give a loving home to a pet in need. Adopt, don’t shop!</p></div><div class="od-heading-art">@include('owner.partials.icon',['name'=>'heart'])<p>“A second chance<br>changes everything.”</p><img src="{{ asset('images/owner/companions-banner.png') }}" alt=""></div></div>
<div class="od-layout"><div><nav class="od-species-tabs" aria-label="Adoption species"><a class="{{ !request('species_id')?'active':'' }}" href="{{ route('owner.browse-adoption',request()->except(['species_id','breed_id','page'])) }}">@include('owner.partials.icon',['name'=>'grid-fill']) All Pets ({{ $total }})</a>@foreach($counts as $group)@php($speciesIcon=strtolower($group->species?->name??''))<a class="{{ request('species_id')==$group->species_id?'active':'' }}" href="{{ route('owner.browse-adoption',array_merge(request()->except(['species_id','breed_id','page']),['species_id'=>$group->species_id])) }}">@include('owner.partials.icon',['name'=>in_array($speciesIcon,['dog','cat','rabbit'])?$speciesIcon:'paw']) {{ Str::plural($group->species?->name??'Other') }} ({{ $group->total }})</a>@endforeach</nav>
<div class="od-adopt-grid">@forelse($listings as $listing)<article class="od-animal"><div class="od-animal-cover">@include('owner.partials.discovery-photo',['path'=>$listing->images->first()?->image_path,'label'=>$listing->pet_name])<button class="od-favorite" type="button" data-favorite="{{ route('owner.favorites.store',['kind'=>'pet','target'=>$listing->id]) }}" aria-label="Save {{ $listing->pet_name }} to favorites" aria-pressed="{{ in_array($listing->id,$favorites)?'true':'false' }}"><i class="bi bi-heart{{ in_array($listing->id,$favorites)?'-fill':'' }}"></i></button></div>
<span class="op-badge {{ $listing->health_state==='under_treatment'?'od-tone-amber':($listing->status==='pending'?'od-tone-purple':'op-green') }}">{{ $listing->health_state==='under_treatment'?'Under Treatment':($listing->status==='pending'?'Under Review':'Available') }}</span><h2>{{ $listing->pet_name }}</h2><p>{{ $listing->breed?->name?:$listing->species?->name }}</p><div class="od-animal-meta"><span><i class="bi bi-calendar3"></i> {{ $listing->age?:'Age not listed' }}</span><span><i class="bi bi-gender-{{ $listing->gender==='female'?'female':'male' }}"></i> {{ ucfirst($listing->gender??'Unknown') }}</span><span><i class="bi bi-geo-alt-fill"></i> {{ $listing->shelter->shelterProfile?->city?:'Location not listed' }}</span></div><a class="op-button op-primary" href="{{ route('owner.adoption.show',$listing) }}">View Details <i class="bi bi-arrow-right"></i></a></article>@empty<div class="op-empty" style="grid-column:1/-1">No pets match your filters.<br><a href="{{ route('owner.browse-adoption') }}">Clear all filters</a></div>@endforelse</div>@include('owner.partials.pagination',['items'=>$listings])
</div><aside class="od-aside"><section class="od-side-card"><div class="od-section-header"><h2>@include('owner.partials.icon',['name'=>'funnel']) Filter Pets</h2><a class="od-clear" href="{{ route('owner.browse-adoption') }}">Clear All</a></div><form class="od-fields" action="{{ route('owner.browse-adoption') }}" method="GET">
@if(request()->filled('search'))<input type="hidden" name="search" value="{{ request('search') }}">@endif
<div><label for="adoptSpecies">Species</label><select id="adoptSpecies" name="species_id" data-adoption-species><option value="">All Species</option>@foreach($species as $item)<option value="{{ $item->id }}" @selected(request('species_id')==$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label for="adoptBreed">Breed</label><select id="adoptBreed" name="breed_id" data-adoption-breed><option value="">All Breeds</option>@foreach($breeds as $item)<option value="{{ $item->id }}" data-species="{{ $item->species_id }}" @selected(request('breed_id')==$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label for="adoptAge">Age Range</label><select id="adoptAge" name="age"><option value="">Any Age</option>@foreach(['baby'=>'Under 1 year','young'=>'1–3 years','adult'=>'3–7 years','senior'=>'7+ years'] as $value=>$label)<option value="{{ $value }}" @selected(request('age')===$value)>{{ $label }}</option>@endforeach</select></div>
<div><label for="adoptGender">Gender</label><select id="adoptGender" name="gender"><option value="">Any Gender</option>@foreach(['male'=>'Male','female'=>'Female'] as $value=>$label)<option value="{{ $value }}" @selected(request('gender')===$value)>{{ $label }}</option>@endforeach</select></div>
<div><label for="adoptLocation">Location</label><select id="adoptLocation" name="location"><option value="">All Cities</option>@foreach($locations as $city)<option @selected(request('location')===$city)>{{ $city }}</option>@endforeach</select></div>
<div><label for="adoptHealth">Health Status</label><select id="adoptHealth" name="health_status"><option value="">All Status</option>@foreach(['healthy'=>'Healthy','under_treatment'=>'Under Treatment','vaccination_due'=>'Vaccination Due'] as $value=>$label)<option value="{{ $value }}" @selected(request('health_status')===$value)>{{ $label }}</option>@endforeach</select></div>
<label class="od-saved-filter"><input type="checkbox" name="favorites" value="1" @checked(request('favorites'))> Saved pets only</label><button class="op-button op-primary" type="submit">Apply Filters</button></form></section>
<section class="od-info-card">@include('owner.partials.icon',['name'=>'paw'])<div><h2>Why Adopt?</h2><ul>@foreach(['You save a life','You give a second chance','You get a loyal companion','You support animal shelters'] as $text)<li><i class="bi bi-check-lg"></i>{{ $text }}</li>@endforeach</ul></div></section></aside></div>
@include('owner.partials.discovery-banner',['bannerTitle'=>'Be the reason','bannerSubtitle'=>'for a happier tomorrow.','bannerText'=>'Open your heart. Adopt a pet.','bannerMessage'=>'Adopt. Love. Care. Repeat. ♥'])
</div>
@include('owner.partials.discovery-scripts')
@endsection
